using System.Text;

namespace FLang.CLI.FFI;

/// <summary>
/// Generates FLang source code from parsed C header information.
/// Produces #foreign fn, #foreign struct, and pub const declarations.
/// </summary>
public class FLangBindingGenerator
{
    public string Generate(CHeaderParseResult parseResult, string headerName)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"// Generated by FLang FFI from {headerName}.h");
        sb.AppendLine();

        // Foreign structs
        if (parseResult.Structs.Count > 0)
        {
            foreach (var s in parseResult.Structs)
            {
                sb.AppendLine($"pub type {s.Name} = #foreign struct {{");
                for (var i = 0; i < s.Fields.Count; i++)
                {
                    var field = s.Fields[i];
                    var comma = i < s.Fields.Count - 1 ? "," : "";
                    sb.AppendLine($"    {field.Name}: {TypeToFlang(field.Type)}{comma}");
                }
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        // Foreign functions
        if (parseResult.Functions.Count > 0)
        {
            foreach (var fn in parseResult.Functions)
            {
                var paramList = string.Join(", ", fn.Parameters.Select(p =>
                    $"{SanitizeIdentifier(p.Name)}: {TypeToFlang(p.Type)}"));
                var returnType = fn.ReturnType.Kind == CTypeKind.Void
                    ? ""
                    : $" {TypeToFlang(fn.ReturnType)}";
                sb.AppendLine($"#foreign fn {fn.Name}({paramList}){returnType}");
            }
            sb.AppendLine();
        }

        // Enum constants
        if (parseResult.EnumConstants.Count > 0)
        {
            foreach (var c in parseResult.EnumConstants)
            {
                sb.AppendLine($"pub const {c.Name}: i32 = {c.Value}");
            }
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string TypeToFlang(CType type) => type.Kind switch
    {
        CTypeKind.Void => "void",
        CTypeKind.Bool => "bool",
        CTypeKind.I8 => "i8",
        CTypeKind.U8 => "u8",
        CTypeKind.I16 => "i16",
        CTypeKind.U16 => "u16",
        CTypeKind.I32 => "i32",
        CTypeKind.U32 => "u32",
        CTypeKind.I64 => "i64",
        CTypeKind.U64 => "u64",
        CTypeKind.F32 => "f32",
        CTypeKind.F64 => "f64",
        CTypeKind.USize => "usize",
        CTypeKind.ISize => "isize",
        CTypeKind.Pointer when type.PointeeType?.Kind == CTypeKind.Unknown => "&u8",
        CTypeKind.Pointer => $"&{TypeToFlang(type.PointeeType!)}",
        CTypeKind.Struct => type.Name!,
        _ => "u8"
    };

    /// <summary>
    /// FLang keywords that can't be used as parameter names.
    /// </summary>
    private static readonly HashSet<string> _reservedWords =
    [
        "type", "fn", "let", "const", "if", "else", "while", "for", "return",
        "true", "false", "pub", "import", "struct", "enum", "match", "in",
        "break", "continue", "test", "null"
    ];

    private static string SanitizeIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name)) return "_";
        if (_reservedWords.Contains(name)) return $"_{name}";
        return name;
    }
}
