using System.Text;
using FLang.Core;
using FLang.IR;
using FLang.IR.Instructions;

namespace FLang.Codegen.C;

/// <summary>
/// Generates C code from an IrModule (new HM pipeline).
/// Consumes only IrType — no TypeBase references.
/// </summary>
public static class HmCCodeGenerator
{
    // Tracks the last emitted #line for diagnostics
    private struct LineState
    {
        public int Line;
        public int FileId;
    }
    public static string GenerateProgram(IrModule module)
    {
        var sb = new StringBuilder();

        // Preamble
        sb.AppendLine("/* Generated by FLang (HM pipeline) */");
        sb.AppendLine("#include <stdio.h>");
        sb.AppendLine("#include <stdlib.h>");
        sb.AppendLine("#include <stdbool.h>");
        sb.AppendLine("#include <stdint.h>");
        sb.AppendLine("#include <string.h>");
        sb.AppendLine("#ifdef _WIN32");
        sb.AppendLine("#include <io.h>");
        sb.AppendLine("#include <fcntl.h>");
        sb.AppendLine("#else");
        sb.AppendLine("#include <unistd.h>");
        sb.AppendLine("#include <fcntl.h>");
        sb.AppendLine("#endif");
        sb.AppendLine();

        // Type forward declarations
        foreach (var td in module.TypeDefs)
        {
            if (td is IrStruct s)
                sb.AppendLine($"typedef struct {s.CName} {s.CName};");
            else if (td is IrEnum e)
                sb.AppendLine($"typedef struct {e.CName} {e.CName};");
        }
        if (module.TypeDefs.Count > 0)
            sb.AppendLine();

        // Type definitions
        foreach (var td in module.TypeDefs)
            EmitTypeDef(sb, td);

        // String table
        EmitStringTable(sb, module);

        // Foreign declarations
        foreach (var decl in module.ForeignDecls)
            EmitForeignDecl(sb, decl);

        // Function forward declarations
        foreach (var fn in module.Functions)
            EmitFunctionForwardDecl(sb, fn);
        if (module.Functions.Count > 0)
            sb.AppendLine();

        // Global constants
        foreach (var gv in module.GlobalValues)
            EmitGlobalValue(sb, gv);
        if (module.GlobalValues.Count > 0)
            sb.AppendLine();

        // Function definitions
        foreach (var fn in module.Functions)
            EmitFunction(sb, fn, module);

        return sb.ToString();
    }

    // =========================================================================
    // Type definitions
    // =========================================================================

    private static void EmitTypeDef(StringBuilder sb, IrType type)
    {
        switch (type)
        {
            case IrStruct s:
                sb.AppendLine($"struct {s.CName} {{");
                foreach (var f in s.Fields)
                {
                    sb.AppendLine($"    {EmitFieldDecl(f.Type, f.Name)};");
                }
                if (s.Fields.Length == 0)
                {
                    sb.AppendLine("    char __empty;");
                }
                sb.AppendLine("};");
                sb.AppendLine();
                break;

            case IrEnum e:
                sb.AppendLine($"struct {e.CName} {{");
                sb.AppendLine("    int32_t tag;");
                // Find largest payload
                var maxPayload = 0;
                foreach (var v in e.Variants)
                    if (v.PayloadType != null && v.PayloadType.Size > maxPayload)
                        maxPayload = v.PayloadType.Size;
                if (maxPayload > 0)
                    sb.AppendLine($"    uint8_t payload[{maxPayload}];");
                sb.AppendLine("};");
                // Tag constants
                foreach (var v in e.Variants)
                    sb.AppendLine($"#define {e.CName}_{v.Name} {v.TagValue}");
                sb.AppendLine();
                break;
        }
    }

    // =========================================================================
    // String table
    // =========================================================================

    // =========================================================================
    // Global constants
    // =========================================================================

    private static void EmitGlobalValue(StringBuilder sb, GlobalValue gv)
    {
        if (gv.Initializer is StructConstantValue scv)
        {
            var irType = scv.IrType;
            if (irType == null) return;

            sb.Append($"static {IrTypeToCType(irType)} {gv.Name} = {{ ");
            if (irType is IrStruct irStruct)
            {
                var parts = new List<string>();
                foreach (var field in irStruct.Fields)
                {
                    if (scv.FieldValues.TryGetValue(field.Name, out var fv))
                        parts.Add($".{field.Name} = {EmitGlobalFieldValue(fv, field.Type)}");
                    else
                        parts.Add($".{field.Name} = {{0}}");
                }
                sb.Append(string.Join(", ", parts));
            }
            sb.AppendLine(" };");
        }
        else if (gv.Initializer is ArrayConstantValue acv && acv.Elements != null && acv.IrType is IrArray arrTy)
        {
            var elemType = arrTy.Element;
            sb.Append($"static {IrTypeToCType(elemType)} {gv.Name}[{acv.Elements.Length}] = {{ ");
            var parts = new List<string>();
            foreach (var elem in acv.Elements)
            {
                if (elem is StructConstantValue elemScv && elemScv.IrType is IrStruct elemStruct)
                    parts.Add(EmitNestedStructConstant(elemScv, elemStruct));
                else
                    parts.Add("{0}");
            }
            sb.Append(string.Join(", ", parts));
            sb.AppendLine(" };");
        }
    }

    private static string EmitGlobalFieldValue(Value value, IrType targetType)
    {
        return value switch
        {
            ConstantValue cv => EmitConstant(cv),
            FunctionReferenceValue fv => fv.IrType is IrFunctionPtr fp2
                ? IrNameMangling.MangleFunctionName(fv.Name, fp2.Params)
                : fv.Name,
            StructConstantValue nested when nested.IrType is IrStruct nestedStruct
                => EmitNestedStructConstant(nested, nestedStruct),
            ArrayConstantValue arr when arr.Data != null
                => $"(uint8_t*)\"{EscapeString(arr.StringRepresentation ?? "")}\"",
            GlobalValue gv when gv.Initializer is ArrayConstantValue
                => gv.Name,
            GlobalValue gv when gv.Initializer is StructConstantValue
                => targetType is IrPointer
                    ? $"({IrTypeToCType(targetType)})&{gv.Name}"
                    : $"&{gv.Name}",
            GlobalValue gv => $"&{gv.Name}",
            _ => "{0}"
        };
    }

    private static string EmitNestedStructConstant(StructConstantValue scv, IrStruct irStruct)
    {
        var parts = new List<string>();
        foreach (var field in irStruct.Fields)
        {
            if (scv.FieldValues.TryGetValue(field.Name, out var fv))
                parts.Add($".{field.Name} = {EmitGlobalFieldValue(fv, field.Type)}");
            else
                parts.Add($".{field.Name} = {{0}}");
        }
        return $"{{ {string.Join(", ", parts)} }}";
    }

    private static void EmitStringTable(StringBuilder sb, IrModule module)
    {
        if (module.StringTable.Count == 0) return;

        sb.AppendLine($"static const core_string_String __flang__string_table[{module.StringTable.Count}] = {{");
        for (var i = 0; i < module.StringTable.Count; i++)
        {
            var entry = module.StringTable[i];
            var escaped = EscapeString(entry.Value);
            var comma = i < module.StringTable.Count - 1 ? "," : "";
            sb.AppendLine($"    {{ (uint8_t*)\"{escaped}\", {entry.Utf8Data.Length - 1} }}{comma}");
        }
        sb.AppendLine("};");
        sb.AppendLine();
    }

    // =========================================================================
    // Foreign declarations
    // =========================================================================

    private static void EmitForeignDecl(StringBuilder sb, IrForeignDecl decl)
    {
        // Most foreign functions come from C headers — skip declarations for common ones
        // Only emit if it's not a standard C function
    }

    // =========================================================================
    // Function forward declarations + definitions
    // =========================================================================

    private static void EmitFunctionForwardDecl(StringBuilder sb, IrFunction fn)
    {
        var retType = IrTypeToCType(fn.ReturnType);
        var name = MangleFunctionName(fn);
        var parms = string.Join(", ", fn.Params.Select(p => EmitVarDecl(p.Type, p.Name)));
        if (string.IsNullOrEmpty(parms)) parms = "void";
        sb.AppendLine($"{retType} {name}({parms});");
    }

    private static void EmitFunction(StringBuilder sb, IrFunction fn, IrModule module)
    {
        var retType = IrTypeToCType(fn.ReturnType);
        var name = fn.IsEntryPoint ? "main" : MangleFunctionName(fn);
        var parms = string.Join(", ", fn.Params.Select(p => EmitVarDecl(p.Type, p.Name)));
        if (string.IsNullOrEmpty(parms)) parms = "void";

        sb.AppendLine($"{retType} {name}({parms}) {{");

        var lineState = new LineState { Line = -1, FileId = -1 };
        foreach (var block in fn.BasicBlocks)
        {
            sb.AppendLine($"  {block.Label}:;");
            foreach (var inst in block.Instructions)
            {
                EmitLineDirective(sb, inst.Span, module.SourceFiles, ref lineState);
                EmitInstruction(sb, inst);
            }
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    // =========================================================================
    // #line directives
    // =========================================================================

    private static void EmitLineDirective(StringBuilder sb, SourceSpan span, IReadOnlyList<Source> sourceFiles, ref LineState state)
    {
        if (span.FileId < 0 || span.FileId >= sourceFiles.Count) return;

        var source = sourceFiles[span.FileId];
        var line = source.GetLineNumber(span.Index) + 1; // #line is 1-based

        // Only include filename when the file changes
        if (span.FileId != state.FileId)
        {
            var path = source.FileName.Replace("\\", "\\\\");
            sb.AppendLine($"#line {line} \"{path}\"");
        }
        else
        {
            sb.AppendLine($"#line {line}");
        }

        state.Line = line;
        state.FileId = span.FileId;
    }

    // =========================================================================
    // Instruction emission
    // =========================================================================

    private static void EmitInstruction(StringBuilder sb, Instruction inst)
    {
        switch (inst)
        {
            case AllocaInstruction alloca:
                {
                    var resultName = alloca.Result.Name;
                    var irType = alloca.Result.IrType;
                    if (alloca.IsArrayStorage && irType is IrPointer { Pointee: IrArray arr })
                    {
                        // Array data alloca: emit actual C array for the storage
                        var elemC = IrTypeToCType(arr.Element);
                        var length = Math.Max(arr.Length ?? 0, 1); // minimum 1 for MSVC
                        sb.AppendLine($"    {elemC} _store_{resultName}[{length}];");
                        sb.AppendLine($"    {elemC}* {resultName} = _store_{resultName};");
                    }
                    else if (irType is IrPointer ptr)
                    {
                        sb.AppendLine($"    {EmitVarDecl(ptr.Pointee, $"_store_{resultName}")};");
                        sb.AppendLine($"    {EmitVarDecl(irType, resultName)} = &_store_{resultName};");
                    }
                    else
                    {
                        sb.AppendLine($"    uint8_t _store_{resultName}[{alloca.SizeInBytes}];");
                        sb.AppendLine($"    void* {resultName} = _store_{resultName};");
                    }
                    break;
                }

            case StorePointerInstruction store:
                {
                    var ptr = EmitValue(store.Pointer);
                    var val = EmitValue(store.Value);
                    var pointeeType = store.Pointer.IrType is IrPointer p ? p.Pointee : null;
                    if (pointeeType != null)
                    {
                        // Use IrPointer wrapper to handle function pointer syntax correctly
                        var castType = IrTypeToCType(new IrPointer(pointeeType));
                        sb.AppendLine($"    *({castType}){ptr} = {val};");
                    }
                    else
                        sb.AppendLine($"    *{ptr} = {val};");
                    break;
                }

            case LoadInstruction load:
                {
                    var resultName = load.Result.Name;
                    var resultIrType = load.Result.IrType ?? TypeLayoutService.IrI32;
                    var ptr = EmitValue(load.Pointer);
                    var castType = IrTypeToCType(new IrPointer(resultIrType));
                    sb.AppendLine($"    {EmitVarDecl(resultIrType, resultName)} = *({castType}){ptr};");
                    break;
                }

            case ReturnInstruction ret:
                {
                    if (ret.Value.IrType == TypeLayoutService.IrVoidPrim ||
                        ret.Value.IrType == null)
                        sb.AppendLine("    return;");
                    else
                        sb.AppendLine($"    return {EmitValue(ret.Value)};");
                    break;
                }

            case BinaryInstruction bin:
                {
                    var resultName = bin.Result.Name;
                    var resultType = IrTypeToCType(bin.Result.IrType ?? TypeLayoutService.IrI32);
                    var left = EmitValue(bin.Left);
                    var right = EmitValue(bin.Right);
                    if (bin.Operation == BinaryOp.UnsignedShiftRight)
                    {
                        // >>> (logical shift): cast to unsigned, shift, cast back
                        var leftIr = bin.Left.IrType ?? TypeLayoutService.IrI32;
                        var unsignedType = leftIr == TypeLayoutService.IrI32 ? "uint32_t"
                            : leftIr == TypeLayoutService.IrI64 || leftIr == TypeLayoutService.IrISize ? "uint64_t"
                            : leftIr == TypeLayoutService.IrI16 ? "uint16_t"
                            : leftIr == TypeLayoutService.IrI8 ? "uint8_t"
                            : IrTypeToCType(leftIr); // already unsigned
                        sb.AppendLine($"    {resultType} {resultName} = ({resultType})(({unsignedType}){left} >> {right});");
                    }
                    else
                    {
                        var op = BinaryOpToC(bin.Operation);
                        sb.AppendLine($"    {resultType} {resultName} = {left} {op} {right};");
                    }
                    break;
                }

            case UnaryInstruction unary:
                {
                    var resultName = unary.Result.Name;
                    var resultType = IrTypeToCType(unary.Result.IrType ?? TypeLayoutService.IrI32);
                    var operand = EmitValue(unary.Operand);
                    var op = unary.Operation == UnaryOp.Negate ? "-" : "!";
                    sb.AppendLine($"    {resultType} {resultName} = {op}{operand};");
                    break;
                }

            case CallInstruction call:
                {
                    var resultName = call.Result.Name;
                    var resultType = call.Result.IrType ?? TypeLayoutService.IrVoidPrim;
                    var args = string.Join(", ", call.Arguments.Select(a => EmitArg(a, call.IsForeignCall)));
                    var fnName = call.IsForeignCall
                        ? call.FunctionName
                        : IrNameMangling.MangleFunctionName(call.FunctionName,
                            call.CalleeIrParamTypes
                            ?? (IReadOnlyList<IrType>)call.Arguments.Select(a => a.IrType ?? TypeLayoutService.IrI32).ToArray());

                    if (resultType == TypeLayoutService.IrVoidPrim)
                        sb.AppendLine($"    {fnName}({args});");
                    else
                        sb.AppendLine($"    {EmitVarDecl(resultType, resultName)} = {fnName}({args});");
                    break;
                }

            case IndirectCallInstruction indirectCall:
                {
                    var funcPtrExpr = EmitValue(indirectCall.FunctionPointer);
                    var args = string.Join(", ", indirectCall.Arguments.Select(EmitValue));
                    var resultName = indirectCall.Result.Name;
                    var resultType = indirectCall.Result.IrType ?? TypeLayoutService.IrVoidPrim;

                    if (resultType == TypeLayoutService.IrVoidPrim)
                        sb.AppendLine($"    {funcPtrExpr}({args});");
                    else
                        sb.AppendLine($"    {EmitVarDecl(resultType, resultName)} = {funcPtrExpr}({args});");
                    break;
                }

            case CastInstruction cast:
                {
                    var resultName = cast.Result.Name;
                    var resultIrType = cast.Result.IrType ?? TypeLayoutService.IrI32;
                    var resultType = IrTypeToCType(resultIrType);
                    var src = EmitValue(cast.Source);
                    sb.AppendLine($"    {EmitVarDecl(resultIrType, resultName)} = ({resultType}){src};");
                    break;
                }

            case GetElementPtrInstruction gep:
                {
                    var resultName = gep.Result.Name;
                    var resultIrType = gep.Result.IrType ?? TypeLayoutService.IrVoidPrim;
                    var resultType = IrTypeToCType(resultIrType);
                    var basePtr = EmitValue(gep.BasePointer);
                    var offset = EmitValue(gep.ByteOffset);
                    sb.AppendLine($"    {EmitVarDecl(resultIrType, resultName)} = ({resultType})((uint8_t*){basePtr} + {offset});");
                    break;
                }

            case BranchInstruction branch:
                {
                    var cond = EmitValue(branch.Condition);
                    sb.AppendLine($"    if ({cond}) goto {branch.TrueBlock.Label};");
                    sb.AppendLine($"    goto {branch.FalseBlock.Label};");
                    break;
                }

            case JumpInstruction jump:
                sb.AppendLine($"    goto {jump.TargetBlock.Label};");
                break;

            case AddressOfInstruction addrOf:
                {
                    var resultName = addrOf.Result.Name;
                    var resultType = IrTypeToCType(addrOf.Result.IrType ?? TypeLayoutService.IrVoidPrim);
                    sb.AppendLine($"    {resultType} {resultName} = &{addrOf.VariableName};");
                    break;
                }

            default:
                sb.AppendLine($"    /* TODO: {inst.GetType().Name} */");
                break;
        }
    }

    // =========================================================================
    // Value emission
    // =========================================================================

    private static string EmitValue(Value value)
    {
        return value switch
        {
            ConstantValue cv => EmitConstant(cv),
            LocalValue lv => lv.Name,
            StringTableValue stv => $"__flang__string_table[{stv.Index}]",
            FunctionReferenceValue fv => fv.IrType is IrFunctionPtr fp
                ? IrNameMangling.MangleFunctionName(fv.Name, fp.Params)
                : fv.Name,
            GlobalValue gv when gv.Initializer is StructConstantValue
                => $"&{gv.Name}",
            GlobalValue gv => gv.Name,
            _ => $"/* unknown value: {value.GetType().Name} */"
        };
    }

    /// <summary>
    /// Emit an integer constant with the appropriate C suffix for its type.
    /// </summary>
    private static string EmitConstant(ConstantValue cv)
    {
        var lit = cv.IntValue.ToString();
        if (cv.IrType is IrPrimitive p)
        {
            if (p == TypeLayoutService.IrU64 || p == TypeLayoutService.IrUSize)
                return lit + "ULL";
            if (p == TypeLayoutService.IrI64 || p == TypeLayoutService.IrISize)
                return lit + "LL";
            if (p == TypeLayoutService.IrU32)
                return lit + "U";
        }
        return lit;
    }

    /// <summary>
    /// Emit a value as a call argument. For foreign calls, casts uint8_t* to (char*)
    /// to avoid clang -Wpointer-sign warnings (FLang uses u8 for bytes, C uses char).
    /// Uses (char*) not (const char*) so it's compatible with both const and non-const params.
    /// </summary>
    private static string EmitArg(Value value, bool isForeignCall)
    {
        var emitted = EmitValue(value);
        if (isForeignCall && value.IrType is IrPointer { Pointee: IrPrimitive p } && p == TypeLayoutService.IrU8)
            return $"(char*){emitted}";
        return emitted;
    }

    // =========================================================================
    // Type mapping
    // =========================================================================

    /// <summary>
    /// Emit a C field/variable declaration. Handles function pointer syntax:
    /// C requires `ret (*name)(params)` not `ret(*)(params) name`.
    /// </summary>
    private static string EmitFieldDecl(IrType type, string name)
    {
        if (type is IrFunctionPtr fp)
        {
            var ret = IrTypeToCType(fp.Return);
            var parms = string.Join(", ", fp.Params.Select(IrTypeToCType));
            return $"{ret} (*{name})({parms})";
        }
        return $"{IrTypeToCType(type)} {name}";
    }

    private static string IrTypeToCType(IrType? type)
    {
        return type switch
        {
            null => "void",
            IrPrimitive p => p.Name switch
            {
                "void" => "void",
                "never" => "void",
                "bool" => "bool",
                "i8" => "int8_t",
                "i16" => "int16_t",
                "i32" => "int32_t",
                "i64" => "int64_t",
                "u8" => "uint8_t",
                "u16" => "uint16_t",
                "u32" => "uint32_t",
                "u64" => "uint64_t",
                "isize" => "int64_t",
                "usize" => "uint64_t",
                "char" => "uint32_t",
                _ => "int32_t"
            },
            IrPointer ptr when ptr.Pointee is IrFunctionPtr fp2 =>
                $"{IrTypeToCType(fp2.Return)}(**)({string.Join(", ", fp2.Params.Select(IrTypeToCType))})",
            IrPointer ptr => $"{IrTypeToCType(ptr.Pointee)}*",
            IrArray arr => $"{IrTypeToCType(arr.Element)}*",
            IrStruct s => s.CName,
            IrEnum e => e.CName,
            IrFunctionPtr fp =>
                $"{IrTypeToCType(fp.Return)}(*)({string.Join(", ", fp.Params.Select(IrTypeToCType))})",
            _ => "void"
        };
    }

    private static string BinaryOpToC(BinaryOp op)
    {
        return op switch
        {
            BinaryOp.Add => "+",
            BinaryOp.Subtract => "-",
            BinaryOp.Multiply => "*",
            BinaryOp.Divide => "/",
            BinaryOp.Modulo => "%",
            BinaryOp.Equal => "==",
            BinaryOp.NotEqual => "!=",
            BinaryOp.LessThan => "<",
            BinaryOp.GreaterThan => ">",
            BinaryOp.LessThanOrEqual => "<=",
            BinaryOp.GreaterThanOrEqual => ">=",
            BinaryOp.BitwiseAnd => "&",
            BinaryOp.BitwiseOr => "|",
            BinaryOp.BitwiseXor => "^",
            BinaryOp.ShiftLeft => "<<",
            BinaryOp.ShiftRight => ">>",
            _ => "/* unknown op */"
        };
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    private static string MangleFunctionName(IrFunction fn)
    {
        return IrNameMangling.MangleFunctionName(fn.Name, [.. fn.Params.Select(p => p.Type)]);
    }

    /// <summary>
    /// Emit a C variable/parameter declaration. Function pointer types and pointers
    /// to function pointers need the name embedded: ret(*name)(params), ret(**name)(params).
    /// </summary>
    private static string EmitVarDecl(IrType type, string name)
    {
        if (type is IrFunctionPtr fp)
        {
            var ret = IrTypeToCType(fp.Return);
            var parms = string.Join(", ", fp.Params.Select(IrTypeToCType));
            return $"{ret}(*{name})({parms})";
        }
        if (type is IrPointer { Pointee: IrFunctionPtr fp2 })
        {
            var ret = IrTypeToCType(fp2.Return);
            var parms = string.Join(", ", fp2.Params.Select(IrTypeToCType));
            return $"{ret}(**{name})({parms})";
        }
        return $"{IrTypeToCType(type)} {name}";
    }

    private static string EscapeString(string s)
    {
        return new StringBuilder(s)
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t")
            .Replace("\0", "\\0")
            .ToString();
    }
}
