using System.Text;
using FLang.Core;
using FLang.IR;
using FLang.IR.Instructions;

namespace FLang.Codegen.C;

/// <summary>
/// Generates C code from an IrModule (new HM pipeline).
/// Consumes only IrType — no TypeBase references.
/// </summary>
public static class HmCCodeGenerator
{
    // Tracks the last emitted #line for diagnostics
    private struct LineState
    {
        public int Line;
        public int FileId;
    }
    public static string GenerateProgram(IrModule module)
    {
        var sb = new StringBuilder();

        // Detect test mode: look for __test_N__ functions
        var testFunctions = module.Functions
            .Where(f => f.Name.StartsWith("__test_") && f.Name.EndsWith("__"))
            .ToList();
        var isTestMode = testFunctions.Count > 0;

        // Preamble
        sb.AppendLine("/* Generated by FLang (HM pipeline) */");
        sb.AppendLine("#include <stdio.h>");
        sb.AppendLine("#include <stdlib.h>");
        sb.AppendLine("#include <stdbool.h>");
        sb.AppendLine("#include <stdint.h>");
        sb.AppendLine("#include <string.h>");
        sb.AppendLine("#include <math.h>");
        if (isTestMode)
            sb.AppendLine("#include <setjmp.h>");
        sb.AppendLine("#ifdef _WIN32");
        sb.AppendLine("#include <io.h>");
        sb.AppendLine("#include <fcntl.h>");
        sb.AppendLine("#else");
        sb.AppendLine("#include <unistd.h>");
        sb.AppendLine("#include <fcntl.h>");
        sb.AppendLine("#include <sys/ioctl.h>");
        sb.AppendLine("#endif");
        sb.AppendLine();

        // Runtime globals: argc/argv capture for std.env
        sb.AppendLine("/* Runtime: argc/argv */");
        sb.AppendLine("static int __flang_argc = 0;");
        sb.AppendLine("static char** __flang_argv = 0;");
        sb.AppendLine("int __flang_get_argc(void) { return __flang_argc; }");
        sb.AppendLine("uint8_t* __flang_get_arg(int index) {");
        sb.AppendLine("    if (index < 0 || index >= __flang_argc) return 0;");
        sb.AppendLine("    return (uint8_t*)__flang_argv[index];");
        sb.AppendLine("}");
        sb.AppendLine("uint8_t* __flang_getenv(const char* name) {");
        sb.AppendLine("    return (uint8_t*)getenv(name);");
        sb.AppendLine("}");
        sb.AppendLine();

        // Test mode globals
        if (isTestMode)
        {
            sb.AppendLine("/* Test infrastructure */");
            sb.AppendLine("static jmp_buf __flang_test_jmpbuf;");
            sb.AppendLine("static volatile int __flang_test_active = 0;");
            sb.AppendLine("static const char* __flang_current_test = \"\";");
            sb.AppendLine();
        }

        // Topological sort: structs/enums used by value must be defined before their users
        var sortedTypes = TopologicalSortTypes(module.TypeDefs);

        // Type forward declarations
        foreach (var td in sortedTypes)
        {
            if (td is IrStruct s)
                sb.AppendLine($"typedef struct {s.CName} {s.CName};");
            else if (td is IrEnum e)
                sb.AppendLine($"typedef struct {e.CName} {e.CName};");
        }
        if (sortedTypes.Count > 0)
            sb.AppendLine();

        // Type definitions
        foreach (var td in sortedTypes)
            EmitTypeDef(sb, td);

        // String table
        EmitStringTable(sb, module);

        // Foreign declarations
        foreach (var decl in module.ForeignDecls)
            EmitForeignDecl(sb, decl);

        // Function forward declarations
        foreach (var fn in module.Functions)
        {
            if (isTestMode && fn.IsEntryPoint) continue; // skip IR-generated test main
            EmitFunctionForwardDecl(sb, fn);
        }
        if (module.Functions.Count > 0)
            sb.AppendLine();

        // Global forward declarations (needed for cross-referencing RTTI globals)
        foreach (var gv in module.GlobalValues)
            EmitGlobalForwardDecl(sb, gv);

        // Global constants
        foreach (var gv in module.GlobalValues)
            EmitGlobalValue(sb, gv, module.StringTable);
        if (module.GlobalValues.Count > 0)
            sb.AppendLine();

        // Function definitions
        foreach (var fn in module.Functions)
        {
            if (isTestMode && fn.IsEntryPoint) continue; // skip IR-generated test main
            EmitFunction(sb, fn, module, isTestMode);
        }

        // Test mode: emit custom C test main
        if (isTestMode)
        {
            // Extract test display names from the IR entry point's printf calls.
            // Pattern: printf("test N/total: <name>... ") followed by call to __test_N__
            var testEntries = ExtractTestEntries(module, testFunctions);
            EmitTestMain(sb, testEntries, module);
        }

        return sb.ToString();
    }

    // =========================================================================
    // Type ordering (topological sort for by-value dependencies)
    // =========================================================================

    /// <summary>
    /// Topologically sort type definitions so that struct/enum types used by value
    /// appear before the types that contain them. Pointer dependencies are excluded
    /// because forward declarations satisfy them.
    /// </summary>
    private static List<IrType> TopologicalSortTypes(List<IrType> typeDefs)
    {
        if (typeDefs.Count <= 1) return typeDefs;

        // Map CName → IrType for lookup
        var nameToType = new Dictionary<string, IrType>(typeDefs.Count);
        foreach (var td in typeDefs)
        {
            var name = td switch { IrStruct s => s.CName, IrEnum e => e.CName, _ => null };
            if (name != null) nameToType[name] = td;
        }

        // Build dependency edges: deps[type] = set of types it depends on (by value)
        var deps = new Dictionary<IrType, List<IrType>>(typeDefs.Count);
        foreach (var td in typeDefs)
        {
            var byValueDeps = new List<IrType>();
            CollectByValueDeps(td, byValueDeps, nameToType);
            deps[td] = byValueDeps;
        }

        // Kahn's algorithm
        var inDegree = new Dictionary<IrType, int>(typeDefs.Count);
        // Reverse mapping: depOf[dependency] = list of types that depend on it
        var dependents = new Dictionary<IrType, List<IrType>>(typeDefs.Count);
        foreach (var td in typeDefs)
        {
            if (!inDegree.ContainsKey(td)) inDegree[td] = 0;
            if (!dependents.ContainsKey(td)) dependents[td] = [];
        }
        foreach (var (td, depList) in deps)
        {
            foreach (var dep in depList)
            {
                if (inDegree.ContainsKey(dep))
                {
                    inDegree[td]++;
                    dependents[dep].Add(td);
                }
            }
        }

        var queue = new Queue<IrType>();
        foreach (var (td, deg) in inDegree)
            if (deg == 0) queue.Enqueue(td);

        var sorted = new List<IrType>(typeDefs.Count);
        while (queue.Count > 0)
        {
            var td = queue.Dequeue();
            sorted.Add(td);
            foreach (var dependent in dependents[td])
            {
                inDegree[dependent]--;
                if (inDegree[dependent] == 0)
                    queue.Enqueue(dependent);
            }
        }

        // Append any remaining types (cycle — shouldn't happen for valid programs)
        if (sorted.Count < typeDefs.Count)
            foreach (var td in typeDefs)
                if (!sorted.Contains(td))
                    sorted.Add(td);

        return sorted;
    }

    private static void CollectByValueDeps(IrType type, List<IrType> deps, Dictionary<string, IrType> nameToType)
    {
        switch (type)
        {
            case IrStruct s:
                foreach (var f in s.Fields)
                    AddByValueDep(f.Type, deps, nameToType);
                break;
            case IrEnum e:
                foreach (var v in e.Variants)
                    if (v.PayloadType != null)
                        AddByValueDep(v.PayloadType, deps, nameToType);
                break;
        }
    }

    private static void AddByValueDep(IrType fieldType, List<IrType> deps, Dictionary<string, IrType> nameToType)
    {
        switch (fieldType)
        {
            case IrStruct s when nameToType.TryGetValue(s.CName, out var resolved):
                deps.Add(resolved);
                break;
            case IrEnum e when nameToType.TryGetValue(e.CName, out var resolved):
                deps.Add(resolved);
                break;
            case IrArray a:
                AddByValueDep(a.Element, deps, nameToType);
                break;
            // IrPointer, IrPrimitive, IrFunctionPtr: satisfied by forward declarations
        }
    }

    // =========================================================================
    // Type definitions
    // =========================================================================

    private static void EmitTypeDef(StringBuilder sb, IrType type)
    {
        switch (type)
        {
            case IrStruct s:
                sb.AppendLine($"struct {s.CName} {{");
                foreach (var f in s.Fields)
                {
                    sb.AppendLine($"    {EmitFieldDecl(f.Type, f.Name)};");
                }
                if (s.Fields.Length == 0)
                {
                    sb.AppendLine("    char __empty;");
                }
                sb.AppendLine("};");
                sb.AppendLine();
                break;

            case IrEnum e:
                sb.AppendLine($"struct {e.CName} {{");
                sb.AppendLine("    int32_t tag;");
                // Find largest payload
                var maxPayload = 0;
                foreach (var v in e.Variants)
                    if (v.PayloadType != null && v.PayloadType.Size > maxPayload)
                        maxPayload = v.PayloadType.Size;
                if (maxPayload > 0)
                    sb.AppendLine($"    uint8_t payload[{maxPayload}];");
                sb.AppendLine("};");
                // Tag constants
                foreach (var v in e.Variants)
                    sb.AppendLine($"#define {e.CName}_{v.Name} {v.TagValue}");
                sb.AppendLine();
                break;
        }
    }

    // =========================================================================
    // String table
    // =========================================================================

    // =========================================================================
    // Global constants
    // =========================================================================

    private static void EmitGlobalForwardDecl(StringBuilder sb, GlobalValue gv)
    {
        if (gv.Initializer is StructConstantValue scv && scv.IrType != null)
            sb.AppendLine($"static {IrTypeToCType(scv.IrType)} {gv.Name};");
        else if (gv.Initializer is ArrayConstantValue acv && acv.Elements != null && acv.IrType is IrArray arrTy)
            sb.AppendLine($"static {IrTypeToCType(arrTy.Element)} {gv.Name}[{acv.Elements.Length}];");
    }

    private static void EmitGlobalValue(StringBuilder sb, GlobalValue gv, List<StringTableEntry> stringTable)
    {
        if (gv.Initializer is StructConstantValue scv)
        {
            var irType = scv.IrType;
            if (irType == null) return;

            sb.Append($"static {IrTypeToCType(irType)} {gv.Name} = {{ ");
            if (irType is IrStruct irStruct)
            {
                var parts = new List<string>();
                foreach (var field in irStruct.Fields)
                {
                    if (scv.FieldValues.TryGetValue(field.Name, out var fv))
                        parts.Add($".{field.Name} = {EmitGlobalFieldValue(fv, field.Type, stringTable)}");
                    else
                        parts.Add($".{field.Name} = {ZeroInitForType(field.Type)}");
                }
                sb.Append(string.Join(", ", parts));
            }
            else if (irType is IrEnum irEnum)
            {
                sb.Append(EmitEnumConstantBody(scv, irEnum));
            }
            sb.AppendLine(" };");
        }
        else if (gv.Initializer is ArrayConstantValue acv && acv.Elements != null && acv.IrType is IrArray arrTy)
        {
            var elemType = arrTy.Element;
            sb.Append($"static {IrTypeToCType(elemType)} {gv.Name}[{acv.Elements.Length}] = {{ ");
            var parts = new List<string>();
            foreach (var elem in acv.Elements)
            {
                if (elem is StructConstantValue elemScv && elemScv.IrType is IrStruct elemStruct)
                    parts.Add(EmitNestedStructConstant(elemScv, elemStruct, stringTable));
                else
                    parts.Add("{0}");
            }
            sb.Append(string.Join(", ", parts));
            sb.AppendLine(" };");
        }
    }

    private static string EmitGlobalFieldValue(Value value, IrType targetType, List<StringTableEntry> stringTable)
    {
        return value switch
        {
            IntConstantValue cv => EmitConstant(cv),
            FloatConstantValue fcv => EmitFloatConstant(fcv),
            StringTableValue stv => EmitInlineStringLiteral(stringTable[stv.Index]),
            FunctionReferenceValue fv => fv.IrType is IrFunctionPtr fp2
                ? IrNameMangling.MangleFunctionName(fv.Name, fp2.Params)
                : fv.Name,
            StructConstantValue nested when nested.IrType is IrStruct nestedStruct
                => EmitNestedStructConstant(nested, nestedStruct, stringTable),
            StructConstantValue nested when nested.IrType is IrEnum nestedEnum
                => $"{{ {EmitEnumConstantBody(nested, nestedEnum)} }}",
            ArrayConstantValue arr when arr.Data != null
                => $"(uint8_t*)\"{EscapeString(arr.StringRepresentation ?? "")}\"",
            GlobalValue gv when gv.Initializer is ArrayConstantValue
                => gv.Name,
            GlobalValue gv when gv.Initializer is StructConstantValue
                => targetType is IrPointer
                    ? $"({IrTypeToCType(targetType)})&{gv.Name}"
                    : $"&{gv.Name}",
            GlobalValue gv => $"&{gv.Name}",
            _ => ZeroInitForType(targetType)
        };
    }

    /// <summary>Returns "0" for scalar types (pointers, primitives) or "{0}" for composites.</summary>
    private static string ZeroInitForType(IrType? type) =>
        type is IrPointer or IrPrimitive ? "0" : "{0}";

    /// <summary>Inline a string table entry as a C struct literal { (uint8_t*)"...", len }.</summary>
    private static string EmitInlineStringLiteral(StringTableEntry entry)
    {
        var escaped = EscapeString(entry.Value);
        var len = entry.Utf8Data.Length - 1; // exclude null terminator
        return $"{{ (uint8_t*)\"{escaped}\", {len} }}";
    }

    private static string EmitNestedStructConstant(StructConstantValue scv, IrStruct irStruct, List<StringTableEntry> stringTable)
    {
        var parts = new List<string>();
        foreach (var field in irStruct.Fields)
        {
            if (scv.FieldValues.TryGetValue(field.Name, out var fv))
                parts.Add($".{field.Name} = {EmitGlobalFieldValue(fv, field.Type, stringTable)}");
            else
                parts.Add($".{field.Name} = {ZeroInitForType(field.Type)}");
        }
        return $"{{ {string.Join(", ", parts)} }}";
    }

    private static string EmitEnumConstantBody(StructConstantValue scv, IrEnum irEnum)
    {
        // Enum in C is: struct { int32_t tag; uint8_t payload[N]; }
        // For naked variants (no payload), just set the tag
        if (scv.FieldValues.TryGetValue("tag", out var tagVal) && tagVal is IntConstantValue cv)
            return $".tag = {EmitConstant(cv)}";
        return ".tag = 0";
    }

    private static void EmitStringTable(StringBuilder sb, IrModule module)
    {
        if (module.StringTable.Count == 0) return;

        sb.AppendLine($"static const core_string_String __flang__string_table[{module.StringTable.Count}] = {{");
        for (var i = 0; i < module.StringTable.Count; i++)
        {
            var entry = module.StringTable[i];
            var escaped = EscapeString(entry.Value);
            var comma = i < module.StringTable.Count - 1 ? "," : "";
            sb.AppendLine($"    {{ (uint8_t*)\"{escaped}\", {entry.Utf8Data.Length - 1} }}{comma}");
        }
        sb.AppendLine("};");
        sb.AppendLine();
    }

    // =========================================================================
    // Foreign declarations
    // =========================================================================

    private static void EmitForeignDecl(StringBuilder sb, IrForeignDecl decl)
    {
        // Most foreign functions come from C headers — skip declarations for common ones
        // Only emit if it's not a standard C function
    }

    // =========================================================================
    // Function forward declarations + definitions
    // =========================================================================

    private static void EmitFunctionForwardDecl(StringBuilder sb, IrFunction fn)
    {
        var retType = fn.UsesReturnSlot ? "void" : IrTypeToCType(fn.ReturnType);
        var name = fn.IsEntryPoint ? "main" : MangleFunctionName(fn);
        if (fn.IsEntryPoint) retType = "int";
        var parms = string.Join(", ", fn.Params.Select(p =>
            p.IsByRef ? EmitVarDecl(new IrPointer(p.Type), p.Name) : EmitVarDecl(p.Type, p.Name)));
        if (fn.IsEntryPoint)
            parms = "int __argc, char** __argv";
        else if (string.IsNullOrEmpty(parms))
            parms = "void";
        sb.AppendLine($"{retType} {name}({parms});");
    }

    private static void EmitFunction(StringBuilder sb, IrFunction fn, IrModule module, bool isTestMode = false)
    {
        var retType = fn.UsesReturnSlot ? "void" : IrTypeToCType(fn.ReturnType);
        var name = fn.IsEntryPoint ? "main" : MangleFunctionName(fn);
        if (fn.IsEntryPoint) retType = "int";
        var parms = string.Join(", ", fn.Params.Select(p =>
            p.IsByRef ? EmitVarDecl(new IrPointer(p.Type), p.Name) : EmitVarDecl(p.Type, p.Name)));
        if (fn.IsEntryPoint)
            parms = "int __argc, char** __argv";
        else if (string.IsNullOrEmpty(parms))
            parms = "void";
        sb.AppendLine($"{retType} {name}({parms}) {{");

        // Capture argc/argv at program entry
        if (fn.IsEntryPoint)
        {
            sb.AppendLine("    __flang_argc = __argc;");
            sb.AppendLine("    __flang_argv = __argv;");
        }

        // In test mode, intercept the panic function: replace exit(1) with longjmp
        var isPanicFn = isTestMode && fn.Name == "panic";

        var lineState = new LineState { Line = -1, FileId = -1 };
        foreach (var block in fn.BasicBlocks)
        {
            sb.AppendLine($"  {block.Label}:;");
            foreach (var inst in block.Instructions)
            {
                EmitLineDirective(sb, inst.Span, module.SourceFiles, ref lineState);

                // In test mode, replace exit() in panic with longjmp
                if (isPanicFn && inst is CallInstruction { IsForeignCall: true, FunctionName: "exit" })
                {
                    sb.AppendLine("    if (__flang_test_active) { longjmp(__flang_test_jmpbuf, 1); }");
                    EmitInstruction(sb, inst, fn.IsEntryPoint);
                }
                else
                {
                    EmitInstruction(sb, inst, fn.IsEntryPoint);
                }
            }
        }

        if (fn.IsEntryPoint) sb.AppendLine("  return 0;");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    // =========================================================================
    // #line directives
    // =========================================================================

    private static void EmitLineDirective(StringBuilder sb, SourceSpan span, IReadOnlyList<Source> sourceFiles, ref LineState state)
    {
        if (span.FileId < 0 || span.FileId >= sourceFiles.Count) return;

        var source = sourceFiles[span.FileId];
        var line = source.GetLineNumber(span.Index) + 1; // #line is 1-based

        // Only include filename when the file changes
        if (span.FileId != state.FileId)
        {
            var path = source.FileName.Replace("\\", "\\\\");
            sb.AppendLine($"#line {line} \"{path}\"");
        }
        else
        {
            sb.AppendLine($"#line {line}");
        }

        state.Line = line;
        state.FileId = span.FileId;
    }

    // =========================================================================
    // Instruction emission
    // =========================================================================

    private static void EmitInstruction(StringBuilder sb, Instruction inst, bool isEntryPoint = false)
    {
        switch (inst)
        {
            case AllocaInstruction alloca:
                {
                    var resultName = alloca.Result.Name;
                    var irType = alloca.Result.IrType;
                    if (alloca.IsArrayStorage && irType is IrPointer { Pointee: IrArray arr })
                    {
                        // Array data alloca: emit actual C array for the storage
                        var elemC = IrTypeToCType(arr.Element);
                        var length = Math.Max(arr.Length ?? 0, 1); // minimum 1 for MSVC
                        sb.AppendLine($"    {elemC} _store_{resultName}[{length}];");
                        sb.AppendLine($"    {elemC}* {resultName} = _store_{resultName};");
                    }
                    else if (irType is IrPointer ptr)
                    {
                        sb.AppendLine($"    {EmitVarDecl(ptr.Pointee, $"_store_{resultName}")};");
                        sb.AppendLine($"    {EmitVarDecl(irType, resultName)} = &_store_{resultName};");
                    }
                    else
                    {
                        sb.AppendLine($"    uint8_t _store_{resultName}[{alloca.SizeInBytes}];");
                        sb.AppendLine($"    void* {resultName} = _store_{resultName};");
                    }
                    break;
                }

            case StorePointerInstruction store:
                {
                    var ptr = EmitValue(store.Pointer);
                    var val = EmitValue(store.Value);
                    var pointeeType = store.Pointer.IrType is IrPointer p ? p.Pointee : null;
                    if (pointeeType != null)
                    {
                        // Use IrPointer wrapper to handle function pointer syntax correctly
                        var castType = IrTypeToCType(new IrPointer(pointeeType));
                        sb.AppendLine($"    *({castType}){ptr} = {val};");
                    }
                    else
                        sb.AppendLine($"    *{ptr} = {val};");
                    break;
                }

            case LoadInstruction load:
                {
                    var resultName = load.Result.Name;
                    var resultIrType = load.Result.IrType ?? TypeLayoutService.IrI32;
                    var ptr = EmitValue(load.Pointer);
                    var castType = IrTypeToCType(new IrPointer(resultIrType));
                    sb.AppendLine($"    {EmitVarDecl(resultIrType, resultName)} = *({castType}){ptr};");
                    break;
                }

            case ReturnInstruction ret:
                {
                    if (ret.Value.IrType == TypeLayoutService.IrVoidPrim ||
                        ret.Value.IrType == null)
                        sb.AppendLine(isEntryPoint ? "    return 0;" : "    return;");
                    else
                        sb.AppendLine($"    return {EmitValue(ret.Value)};");
                    break;
                }

            case BinaryInstruction bin:
                {
                    var resultName = bin.Result.Name;
                    var resultType = IrTypeToCType(bin.Result.IrType ?? TypeLayoutService.IrI32);
                    var left = EmitValue(bin.Left);
                    var right = EmitValue(bin.Right);
                    if (bin.Operation == BinaryOp.UnsignedShiftRight)
                    {
                        // >>> (logical shift): cast to unsigned, shift, cast back
                        var leftIr = bin.Left.IrType ?? TypeLayoutService.IrI32;
                        var unsignedType = leftIr == TypeLayoutService.IrI32 ? "uint32_t"
                            : leftIr == TypeLayoutService.IrI64 || leftIr == TypeLayoutService.IrISize ? "uint64_t"
                            : leftIr == TypeLayoutService.IrI16 ? "uint16_t"
                            : leftIr == TypeLayoutService.IrI8 ? "uint8_t"
                            : IrTypeToCType(leftIr); // already unsigned
                        sb.AppendLine($"    {resultType} {resultName} = ({resultType})(({unsignedType}){left} >> {right});");
                    }
                    else if (bin.Operation == BinaryOp.Modulo && IsFloatIrType(bin.Left.IrType))
                    {
                        sb.AppendLine($"    {resultType} {resultName} = fmod({left}, {right});");
                    }
                    else
                    {
                        var op = BinaryOpToC(bin.Operation);
                        sb.AppendLine($"    {resultType} {resultName} = {left} {op} {right};");
                    }
                    break;
                }

            case UnaryInstruction unary:
                {
                    var resultName = unary.Result.Name;
                    var resultType = IrTypeToCType(unary.Result.IrType ?? TypeLayoutService.IrI32);
                    var operand = EmitValue(unary.Operand);
                    var op = unary.Operation == UnaryOp.Negate ? "-" : "!";
                    sb.AppendLine($"    {resultType} {resultName} = {op}{operand};");
                    break;
                }

            case CallInstruction call:
                {
                    var resultName = call.Result.Name;
                    var resultType = call.Result.IrType ?? TypeLayoutService.IrVoidPrim;
                    var args = string.Join(", ", call.Arguments.Select(a => EmitArg(a, call.IsForeignCall)));
                    var fnName = call.IsForeignCall
                        ? call.FunctionName
                        : IrNameMangling.MangleFunctionName(call.FunctionName,
                            call.CalleeIrParamTypes
                            ?? (IReadOnlyList<IrType>)call.Arguments.Select(a => a.IrType ?? TypeLayoutService.IrI32).ToArray());

                    if (resultType == TypeLayoutService.IrVoidPrim)
                        sb.AppendLine($"    {fnName}({args});");
                    else
                        sb.AppendLine($"    {EmitVarDecl(resultType, resultName)} = {fnName}({args});");
                    break;
                }

            case IndirectCallInstruction indirectCall:
                {
                    var funcPtrExpr = EmitValue(indirectCall.FunctionPointer);
                    var args = string.Join(", ", indirectCall.Arguments.Select(EmitValue));
                    var resultName = indirectCall.Result.Name;
                    var resultType = indirectCall.Result.IrType ?? TypeLayoutService.IrVoidPrim;

                    if (resultType == TypeLayoutService.IrVoidPrim)
                        sb.AppendLine($"    {funcPtrExpr}({args});");
                    else
                        sb.AppendLine($"    {EmitVarDecl(resultType, resultName)} = {funcPtrExpr}({args});");
                    break;
                }

            case CastInstruction cast:
                {
                    var resultName = cast.Result.Name;
                    var resultIrType = cast.Result.IrType ?? TypeLayoutService.IrI32;
                    var resultType = IrTypeToCType(resultIrType);
                    var src = EmitValue(cast.Source);
                    sb.AppendLine($"    {EmitVarDecl(resultIrType, resultName)} = ({resultType}){src};");
                    break;
                }

            case GetElementPtrInstruction gep:
                {
                    var resultName = gep.Result.Name;
                    var resultIrType = gep.Result.IrType ?? TypeLayoutService.IrVoidPrim;
                    var resultType = IrTypeToCType(resultIrType);
                    var basePtr = EmitValue(gep.BasePointer);
                    var offset = EmitValue(gep.ByteOffset);
                    sb.AppendLine($"    {EmitVarDecl(resultIrType, resultName)} = ({resultType})((uint8_t*){basePtr} + {offset});");
                    break;
                }

            case BranchInstruction branch:
                {
                    var cond = EmitValue(branch.Condition);
                    sb.AppendLine($"    if ({cond}) goto {branch.TrueBlock.Label};");
                    sb.AppendLine($"    goto {branch.FalseBlock.Label};");
                    break;
                }

            case JumpInstruction jump:
                sb.AppendLine($"    goto {jump.TargetBlock.Label};");
                break;

            case AddressOfInstruction addrOf:
                {
                    var resultName = addrOf.Result.Name;
                    var resultType = IrTypeToCType(addrOf.Result.IrType ?? TypeLayoutService.IrVoidPrim);
                    sb.AppendLine($"    {resultType} {resultName} = &{addrOf.VariableName};");
                    break;
                }

            case CopyInstruction copy:
                {
                    var src = EmitValue(copy.SrcPtr);
                    var dst = EmitValue(copy.DstPtr);
                    var castType = IrTypeToCType(new IrPointer(copy.ValueType));
                    sb.AppendLine($"    *({castType}){dst} = *({castType}){src};");
                    break;
                }

            case CopyFromOffsetInstruction cfo:
                {
                    var resultName = cfo.Result.Name;
                    var resultIrType = cfo.Result.IrType ?? TypeLayoutService.IrI32;
                    var src = EmitValue(cfo.SrcPtr);
                    var offset = EmitValue(cfo.ByteOffset);
                    if (resultIrType is IrArray { Length: not null } cfoArr)
                    {
                        // Fixed-size array field: take address, don't dereference
                        var elemType = IrTypeToCType(cfoArr.Element);
                        sb.AppendLine($"    {elemType}* {resultName} = ({elemType}*)((uint8_t*){src} + {offset});");
                    }
                    else
                    {
                        var castType = IrTypeToCType(new IrPointer(resultIrType));
                        sb.AppendLine($"    {EmitVarDecl(resultIrType, resultName)} = *({castType})((uint8_t*){src} + {offset});");
                    }
                    break;
                }

            case CopyToOffsetInstruction cto:
                {
                    var val = EmitValue(cto.Val);
                    var dst = EmitValue(cto.DstPtr);
                    var offset = EmitValue(cto.ByteOffset);
                    var castType = IrTypeToCType(new IrPointer(cto.ValueType));
                    sb.AppendLine($"    *({castType})((uint8_t*){dst} + {offset}) = {val};");
                    break;
                }

            default:
                sb.AppendLine($"    /* TODO: {inst.GetType().Name} */");
                break;
        }
    }

    // =========================================================================
    // Value emission
    // =========================================================================

    private static string EmitValue(Value value)
    {
        return value switch
        {
            IntConstantValue cv => EmitConstant(cv),
            FloatConstantValue fcv => EmitFloatConstant(fcv),
            LocalValue lv => lv.Name,
            StringTableValue stv => $"__flang__string_table[{stv.Index}]",
            FunctionReferenceValue fv => fv.IrType is IrFunctionPtr fp
                ? IrNameMangling.MangleFunctionName(fv.Name, fp.Params)
                : fv.Name,
            RawCStringValue rv => $"\"{rv.Text}\"",
            GlobalValue gv when gv.Initializer is StructConstantValue
                => $"&{gv.Name}",
            GlobalValue gv => gv.Name,
            _ => $"/* unknown value: {value.GetType().Name} */"
        };
    }

    /// <summary>
    /// Emit an integer constant with the appropriate C suffix for its type.
    /// </summary>
    private static string EmitConstant(IntConstantValue cv)
    {
        // INT64_MIN can't be written as -9223372036854775808LL in C because the positive
        // part overflows signed long long. Use the (-MAX - 1) idiom instead.
        if (cv.IntValue == long.MinValue && cv.IrType is IrPrimitive p64
            && (p64 == TypeLayoutService.IrI64 || p64 == TypeLayoutService.IrISize))
            return "(-9223372036854775807LL - 1LL)";

        var lit = cv.IntValue.ToString();
        if (cv.IrType is IrPrimitive p)
        {
            if (p == TypeLayoutService.IrU64 || p == TypeLayoutService.IrUSize)
                return lit + "ULL";
            if (p == TypeLayoutService.IrI64 || p == TypeLayoutService.IrISize)
                return lit + "LL";
            if (p == TypeLayoutService.IrU32)
                return lit + "U";
        }
        return lit;
    }

    /// <summary>
    /// Emit a floating-point constant with the appropriate C suffix.
    /// </summary>
    private static string EmitFloatConstant(FloatConstantValue fcv)
    {
        if (double.IsNaN(fcv.FloatValue))
            return "NAN";
        if (double.IsPositiveInfinity(fcv.FloatValue))
            return "INFINITY";
        if (double.IsNegativeInfinity(fcv.FloatValue))
            return "(-INFINITY)";

        // Use R format for round-trip precision
        var lit = fcv.FloatValue.ToString("R", System.Globalization.CultureInfo.InvariantCulture);
        // Ensure the literal always has a decimal point so C sees it as floating-point
        if (!lit.Contains('.') && !lit.Contains('E') && !lit.Contains('e'))
            lit += ".0";

        if (fcv.IrType == TypeLayoutService.IrF32)
            return lit + "f";
        return lit;
    }

    /// <summary>
    /// Emit a value as a call argument. For foreign calls, casts uint8_t* to (char*)
    /// to avoid clang -Wpointer-sign warnings (FLang uses u8 for bytes, C uses char).
    /// Uses (char*) not (const char*) so it's compatible with both const and non-const params.
    /// </summary>
    private static string EmitArg(Value value, bool isForeignCall)
    {
        var emitted = EmitValue(value);
        if (isForeignCall && value.IrType is IrPointer { Pointee: IrPrimitive p } && p == TypeLayoutService.IrU8)
            return $"(char*){emitted}";
        return emitted;
    }

    // =========================================================================
    // Type mapping
    // =========================================================================

    /// <summary>
    /// Transform an IrFunctionPtr to its ABI form: large value params become pointers,
    /// large return type becomes void with a hidden __ret pointer param.
    /// </summary>
    private static (IrType[] Params, IrType Return) GetAbiFunctionPtr(IrFunctionPtr fp)
    {
        var abiParams = new List<IrType>();
        var usesRetSlot = TypeLayoutService.IsLargeValue(fp.Return);
        if (usesRetSlot)
            abiParams.Add(new IrPointer(fp.Return));
        foreach (var p in fp.Params)
            abiParams.Add(TypeLayoutService.IsLargeValue(p) ? new IrPointer(p) : p);
        return ([.. abiParams], usesRetSlot ? TypeLayoutService.IrVoidPrim : fp.Return);
    }

    /// <summary>
    /// Emit a C field/variable declaration. Handles function pointer syntax:
    /// C requires `ret (*name)(params)` not `ret(*)(params) name`.
    /// </summary>
    private static string EmitFieldDecl(IrType type, string name)
    {
        if (type is IrFunctionPtr fp)
        {
            var (abiParams, abiRet) = GetAbiFunctionPtr(fp);
            var ret = IrTypeToCType(abiRet);
            var parms = string.Join(", ", abiParams.Select(IrTypeToCType));
            return $"{ret} (*{name})({parms})";
        }
        if (type is IrArray { Length: not null } arr)
        {
            return $"{IrTypeToCType(arr.Element)} {name}[{arr.Length}]";
        }
        return $"{IrTypeToCType(type)} {name}";
    }

    private static string IrTypeToCType(IrType? type)
    {
        return type switch
        {
            null => "void",
            IrPrimitive p => p.Name switch
            {
                "void" => "void",
                "never" => "void",
                "bool" => "bool",
                "i8" => "int8_t",
                "i16" => "int16_t",
                "i32" => "int32_t",
                "i64" => "int64_t",
                "u8" => "uint8_t",
                "u16" => "uint16_t",
                "u32" => "uint32_t",
                "u64" => "uint64_t",
                "isize" => "int64_t",
                "usize" => "uint64_t",
                "char" => "uint32_t",
                "f32" => "float",
                "f64" => "double",
                _ => "int32_t"
            },
            IrPointer ptr when ptr.Pointee is IrFunctionPtr fp2 =>
                EmitFuncPtrType(fp2, "**"),
            IrPointer ptr => $"{IrTypeToCType(ptr.Pointee)}*",
            IrArray arr => $"{IrTypeToCType(arr.Element)}*",
            IrStruct s => s.CName,
            IrEnum e => e.CName,
            IrFunctionPtr fp => EmitFuncPtrType(fp, "*"),
            _ => "void"
        };
    }

    private static string EmitFuncPtrType(IrFunctionPtr fp, string indirection)
    {
        var (abiParams, abiRet) = GetAbiFunctionPtr(fp);
        return $"{IrTypeToCType(abiRet)}({indirection})({string.Join(", ", abiParams.Select(IrTypeToCType))})";
    }

    private static string BinaryOpToC(BinaryOp op)
    {
        return op switch
        {
            BinaryOp.Add => "+",
            BinaryOp.Subtract => "-",
            BinaryOp.Multiply => "*",
            BinaryOp.Divide => "/",
            BinaryOp.Modulo => "%",
            BinaryOp.Equal => "==",
            BinaryOp.NotEqual => "!=",
            BinaryOp.LessThan => "<",
            BinaryOp.GreaterThan => ">",
            BinaryOp.LessThanOrEqual => "<=",
            BinaryOp.GreaterThanOrEqual => ">=",
            BinaryOp.BitwiseAnd => "&",
            BinaryOp.BitwiseOr => "|",
            BinaryOp.BitwiseXor => "^",
            BinaryOp.ShiftLeft => "<<",
            BinaryOp.ShiftRight => ">>",
            _ => "/* unknown op */"
        };
    }

    private static bool IsFloatIrType(IrType? type) =>
        type == TypeLayoutService.IrF32 || type == TypeLayoutService.IrF64;

    // =========================================================================
    // Helpers
    // =========================================================================

    private static string MangleFunctionName(IrFunction fn)
    {
        var paramList = fn.UsesReturnSlot ? fn.Params.Skip(1) : fn.Params;
        return IrNameMangling.MangleFunctionName(fn.Name, [.. paramList.Select(p => p.Type)]);
    }

    /// <summary>
    /// Emit a C variable/parameter declaration. Function pointer types and pointers
    /// to function pointers need the name embedded: ret(*name)(params), ret(**name)(params).
    /// </summary>
    private static string EmitVarDecl(IrType type, string name)
    {
        if (type is IrFunctionPtr fp)
        {
            var (abiParams, abiRet) = GetAbiFunctionPtr(fp);
            var ret = IrTypeToCType(abiRet);
            var parms = string.Join(", ", abiParams.Select(IrTypeToCType));
            return $"{ret}(*{name})({parms})";
        }
        if (type is IrPointer { Pointee: IrFunctionPtr fp2 })
        {
            var (abiParams, abiRet) = GetAbiFunctionPtr(fp2);
            var ret = IrTypeToCType(abiRet);
            var parms = string.Join(", ", abiParams.Select(IrTypeToCType));
            return $"{ret}(**{name})({parms})";
        }
        return $"{IrTypeToCType(type)} {name}";
    }

    private static string EscapeString(string s)
    {
        return new StringBuilder(s)
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t")
            .Replace("\0", "\\0")
            .ToString();
    }

    // =========================================================================
    // Test infrastructure
    // =========================================================================

    private record TestEntry(string DisplayName, string CFunctionName);

    /// <summary>
    /// Extract test display names and C function names from the IR entry point.
    /// The IR test main has a pattern: printf("test N/total: name... "), call __test_N__(), printf("ok\n").
    /// We extract the name from the printf format string and pair it with the test function call.
    /// </summary>
    private static List<TestEntry> ExtractTestEntries(IrModule module, List<IrFunction> testFunctions)
    {
        var entries = new List<TestEntry>();
        var entryPoint = module.Functions.FirstOrDefault(f => f.IsEntryPoint);
        if (entryPoint == null)
        {
            // Fallback: use function names as display names
            for (int i = 0; i < testFunctions.Count; i++)
                entries.Add(new TestEntry(testFunctions[i].Name, MangleFunctionName(testFunctions[i])));
            return entries;
        }

        // Walk the entry point instructions to find printf + call pairs
        var allInstructions = entryPoint.BasicBlocks.SelectMany(b => b.Instructions).ToList();
        string? pendingTestName = null;

        foreach (var inst in allInstructions)
        {
            if (inst is CallInstruction { IsForeignCall: true, FunctionName: "printf" } printfCall
                && printfCall.Arguments.Count > 0
                && printfCall.Arguments[0] is RawCStringValue rv)
            {
                // Parse "test N/total: <name>... " -> extract <name>
                var text = rv.Text;
                var colonIdx = text.IndexOf(": ", StringComparison.Ordinal);
                if (colonIdx >= 0 && text.EndsWith("... "))
                {
                    pendingTestName = text[(colonIdx + 2)..^4]; // strip ": " prefix and "... " suffix
                }
            }
            else if (inst is CallInstruction { IsForeignCall: false } call
                     && call.FunctionName.StartsWith("__test_") && call.FunctionName.EndsWith("__"))
            {
                var displayName = pendingTestName ?? call.FunctionName;
                entries.Add(new TestEntry(displayName, call.FunctionName));
                pendingTestName = null;
            }
        }

        // Fallback for any test functions not found in the entry point
        if (entries.Count == 0)
        {
            for (int i = 0; i < testFunctions.Count; i++)
                entries.Add(new TestEntry(testFunctions[i].Name, MangleFunctionName(testFunctions[i])));
        }

        return entries;
    }

    /// <summary>
    /// Emit a custom C main function for test mode with:
    /// - setjmp/longjmp to continue after assertion failures
    /// - fflush(stdout) after each test (pass or fail)
    /// - Current test name printed on failure
    /// - Pass/fail summary at the end
    /// </summary>
    private static void EmitTestMain(StringBuilder sb, List<TestEntry> testEntries, IrModule module)
    {
        var total = testEntries.Count;

        // Look up TestAllocator infrastructure from IR module
        var testAllocState = module.GlobalValues.FirstOrDefault(g => g.Name.EndsWith("test_allocator_state"));
        string? checkLeaksFn = null;
        string? deinitFn = null;
        if (testAllocState != null)
        {
            // Find check_leaks and deinit functions that take &TestAllocatorState
            foreach (var fn in module.Functions)
            {
                var mangledName = MangleFunctionName(fn);
                if (fn.Name.EndsWith("check_leaks") && fn.Params.Count == 1)
                    checkLeaksFn = mangledName;
                else if (fn.Name.EndsWith("deinit") && fn.Params.Count == 1
                         && fn.Params[0].Type is IrPointer p
                         && p.Pointee is IrStruct s
                         && s.CName.Contains("TestAllocatorState"))
                    deinitFn = mangledName;
            }
        }

        sb.AppendLine("/* Test main — generated by FLang test infrastructure */");
        sb.AppendLine("int main(int __argc, char** __argv) {");
        sb.AppendLine("    __flang_argc = __argc;");
        sb.AppendLine("    __flang_argv = __argv;");
        sb.AppendLine($"    int __passed = 0, __failed = 0;");
        sb.AppendLine($"    printf(\"Running {total} test(s)...\\n\");");
        sb.AppendLine();

        for (int i = 0; i < total; i++)
        {
            var entry = testEntries[i];
            var escapedName = EscapeString(entry.DisplayName);

            sb.AppendLine($"    /* test {i + 1}/{total}: {escapedName} */");
            sb.AppendLine($"    __flang_current_test = \"{escapedName}\";");
            sb.AppendLine($"    printf(\"test {i + 1}/{total}: {escapedName}... \");");
            sb.AppendLine($"    __flang_test_active = 1;");
            sb.AppendLine($"    if (setjmp(__flang_test_jmpbuf) == 0) {{");
            sb.AppendLine($"        {entry.CFunctionName}();");
            sb.AppendLine($"        __flang_test_active = 0;");
            sb.AppendLine($"        printf(\"ok\\n\");");
            sb.AppendLine($"        __passed++;");
            sb.AppendLine($"    }} else {{");
            sb.AppendLine($"        __flang_test_active = 0;");
            sb.AppendLine($"        printf(\"FAILED\\n\");");
            sb.AppendLine($"        __failed++;");
            sb.AppendLine($"    }}");

            // After each test: check for leaks, then reset the test allocator
            if (testAllocState != null && checkLeaksFn != null && deinitFn != null)
            {
                sb.AppendLine($"    if ({checkLeaksFn}(&{testAllocState.Name}) > 0) {{");
                sb.AppendLine($"        printf(\"  ^ in test: {escapedName}\\n\");");
                sb.AppendLine($"    }}");
                sb.AppendLine($"    {deinitFn}(&{testAllocState.Name});");
            }

            sb.AppendLine($"    fflush(stdout);");
            sb.AppendLine();
        }

        sb.AppendLine("    printf(\"\\n\");");
        sb.AppendLine("    if (__failed == 0) {");
        sb.AppendLine($"        printf(\"All {total} test(s) passed.\\n\");");
        sb.AppendLine("    } else {");
        sb.AppendLine("        printf(\"%d passed, %d failed out of %d test(s).\\n\", __passed, __failed, __passed + __failed);");
        sb.AppendLine("    }");
        sb.AppendLine("    fflush(stdout);");
        sb.AppendLine("    return __failed > 0 ? 1 : 0;");
        sb.AppendLine("}");
        sb.AppendLine();
    }
}
