using System.Text;
using FLang.Core;
using FLang.IR;
using FLang.IR.Instructions;

namespace FLang.Codegen.C;

/// <summary>
/// Generates C code from an IrModule (new HM pipeline).
/// Consumes only IrType — no TypeBase references.
/// </summary>
public static class HmCCodeGenerator
{
    // Tracks the last emitted #line to avoid redundant directives
    private struct LineState
    {
        public int Line;
        public int FileId;
    }
    public static string GenerateProgram(IrModule module)
    {
        var sb = new StringBuilder();

        // Preamble
        sb.AppendLine("/* Generated by FLang (HM pipeline) */");
        sb.AppendLine("#include <stdio.h>");
        sb.AppendLine("#include <stdlib.h>");
        sb.AppendLine("#include <stdbool.h>");
        sb.AppendLine("#include <stdint.h>");
        sb.AppendLine("#include <string.h>");
        sb.AppendLine();

        // Type forward declarations
        foreach (var td in module.TypeDefs)
        {
            if (td is IrStruct s)
                sb.AppendLine($"typedef struct {s.CName} {s.CName};");
            else if (td is IrEnum e)
                sb.AppendLine($"typedef struct {e.CName} {e.CName};");
        }
        if (module.TypeDefs.Count > 0)
            sb.AppendLine();

        // String type (needed for string table)
        sb.AppendLine("typedef struct { const char* data; int64_t length; } String;");
        sb.AppendLine();

        // Type definitions
        foreach (var td in module.TypeDefs)
            EmitTypeDef(sb, td);

        // String table
        EmitStringTable(sb, module);

        // Foreign declarations
        foreach (var decl in module.ForeignDecls)
            EmitForeignDecl(sb, decl);

        // Function forward declarations
        foreach (var fn in module.Functions)
            EmitFunctionForwardDecl(sb, fn);
        if (module.Functions.Count > 0)
            sb.AppendLine();

        // Function definitions
        foreach (var fn in module.Functions)
            EmitFunction(sb, fn, module);

        return sb.ToString();
    }

    // =========================================================================
    // Type definitions
    // =========================================================================

    private static void EmitTypeDef(StringBuilder sb, IrType type)
    {
        switch (type)
        {
            case IrStruct s:
                sb.AppendLine($"struct {s.CName} {{");
                foreach (var f in s.Fields)
                    sb.AppendLine($"    {IrTypeToCType(f.Type)} {SanitizeName(f.Name)};");
                if (s.Fields.Length == 0)
                    sb.AppendLine("    char __empty;");
                sb.AppendLine("};");
                sb.AppendLine();
                break;

            case IrEnum e:
                sb.AppendLine($"struct {e.CName} {{");
                sb.AppendLine("    int32_t tag;");
                // Find largest payload
                var maxPayload = 0;
                foreach (var v in e.Variants)
                    if (v.PayloadType != null && v.PayloadType.Size > maxPayload)
                        maxPayload = v.PayloadType.Size;
                if (maxPayload > 0)
                    sb.AppendLine($"    uint8_t payload[{maxPayload}];");
                sb.AppendLine("};");
                // Tag constants
                foreach (var v in e.Variants)
                    sb.AppendLine($"#define {e.CName}_{v.Name} {v.TagValue}");
                sb.AppendLine();
                break;
        }
    }

    // =========================================================================
    // String table
    // =========================================================================

    private static void EmitStringTable(StringBuilder sb, IrModule module)
    {
        if (module.StringTable.Count == 0) return;

        sb.AppendLine($"static const String __flang__string_table[{module.StringTable.Count}] = {{");
        for (var i = 0; i < module.StringTable.Count; i++)
        {
            var entry = module.StringTable[i];
            var escaped = EscapeString(entry.Value);
            var comma = i < module.StringTable.Count - 1 ? "," : "";
            sb.AppendLine($"    {{ \"{escaped}\", {entry.Utf8Data.Length - 1} }}{comma}");
        }
        sb.AppendLine("};");
        sb.AppendLine();
    }

    // =========================================================================
    // Foreign declarations
    // =========================================================================

    private static void EmitForeignDecl(StringBuilder sb, IrForeignDecl decl)
    {
        // Most foreign functions come from C headers — skip declarations for common ones
        // Only emit if it's not a standard C function
    }

    // =========================================================================
    // Function forward declarations + definitions
    // =========================================================================

    private static void EmitFunctionForwardDecl(StringBuilder sb, IrFunction fn)
    {
        var retType = IrTypeToCType(fn.ReturnType);
        var name = MangleFunctionName(fn);
        var parms = string.Join(", ", fn.Params.Select(p => $"{IrTypeToCType(p.Type)} {SanitizeName(p.Name)}"));
        if (string.IsNullOrEmpty(parms)) parms = "void";
        sb.AppendLine($"{retType} {name}({parms});");
    }

    private static void EmitFunction(StringBuilder sb, IrFunction fn, IrModule module)
    {
        var retType = IrTypeToCType(fn.ReturnType);
        var name = fn.IsEntryPoint ? "main" : MangleFunctionName(fn);
        var parms = string.Join(", ", fn.Params.Select(p => $"{IrTypeToCType(p.Type)} {SanitizeName(p.Name)}"));
        if (string.IsNullOrEmpty(parms)) parms = "void";

        sb.AppendLine($"{retType} {name}({parms}) {{");

        var lineState = new LineState { Line = -1, FileId = -1 };
        foreach (var block in fn.BasicBlocks)
        {
            sb.AppendLine($"  {block.Label}:;");
            foreach (var inst in block.Instructions)
            {
                EmitLineDirective(sb, inst.Span, module.SourceFiles, ref lineState);
                EmitInstruction(sb, inst);
            }
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    // =========================================================================
    // #line directives
    // =========================================================================

    private static void EmitLineDirective(StringBuilder sb, SourceSpan span, IReadOnlyList<Source> sourceFiles, ref LineState state)
    {
        if (span.FileId < 0 || span.FileId >= sourceFiles.Count) return;

        var source = sourceFiles[span.FileId];
        var line = source.GetLineNumber(span.Index) + 1; // #line is 1-based

        // Skip if same line+file as last directive
        if (line == state.Line && span.FileId == state.FileId) return;

        state.Line = line;
        state.FileId = span.FileId;

        var path = source.FileName.Replace("\\", "\\\\");
        sb.AppendLine($"#line {line} \"{path}\"");
    }

    // =========================================================================
    // Instruction emission
    // =========================================================================

    private static void EmitInstruction(StringBuilder sb, Instruction inst)
    {
        switch (inst)
        {
            case AllocaInstruction alloca:
                {
                    var resultName = SanitizeName(alloca.Result.Name);
                    var irType = alloca.Result.IrType;
                    if (irType is IrPointer ptr)
                    {
                        sb.AppendLine($"    {IrTypeToCType(ptr.Pointee)} _store_{resultName};");
                        sb.AppendLine($"    {IrTypeToCType(irType)} {resultName} = &_store_{resultName};");
                    }
                    else
                    {
                        sb.AppendLine($"    uint8_t _store_{resultName}[{alloca.SizeInBytes}];");
                        sb.AppendLine($"    void* {resultName} = _store_{resultName};");
                    }
                    break;
                }

            case StorePointerInstruction store:
                {
                    var ptr = EmitValue(store.Pointer);
                    var val = EmitValue(store.Value);
                    var pointeeType = store.Pointer.IrType is IrPointer p ? p.Pointee : null;
                    if (pointeeType != null)
                        sb.AppendLine($"    *({IrTypeToCType(pointeeType)}*){ptr} = {val};");
                    else
                        sb.AppendLine($"    *{ptr} = {val};");
                    break;
                }

            case LoadInstruction load:
                {
                    var resultName = SanitizeName(load.Result.Name);
                    var resultType = IrTypeToCType(load.Result.IrType ?? TypeLayoutService.IrI32);
                    var ptr = EmitValue(load.Pointer);
                    sb.AppendLine($"    {resultType} {resultName} = *({resultType}*){ptr};");
                    break;
                }

            case ReturnInstruction ret:
                {
                    if (ret.Value.IrType == TypeLayoutService.IrVoidPrim ||
                        ret.Value.IrType == null)
                        sb.AppendLine("    return;");
                    else
                        sb.AppendLine($"    return {EmitValue(ret.Value)};");
                    break;
                }

            case BinaryInstruction bin:
                {
                    var resultName = SanitizeName(bin.Result.Name);
                    var resultType = IrTypeToCType(bin.Result.IrType ?? TypeLayoutService.IrI32);
                    var left = EmitValue(bin.Left);
                    var right = EmitValue(bin.Right);
                    var op = BinaryOpToC(bin.Operation);
                    sb.AppendLine($"    {resultType} {resultName} = {left} {op} {right};");
                    break;
                }

            case UnaryInstruction unary:
                {
                    var resultName = SanitizeName(unary.Result.Name);
                    var resultType = IrTypeToCType(unary.Result.IrType ?? TypeLayoutService.IrI32);
                    var operand = EmitValue(unary.Operand);
                    var op = unary.Operation == UnaryOp.Negate ? "-" : "!";
                    sb.AppendLine($"    {resultType} {resultName} = {op}{operand};");
                    break;
                }

            case CallInstruction call:
                {
                    var resultName = SanitizeName(call.Result.Name);
                    var resultType = call.Result.IrType ?? TypeLayoutService.IrVoidPrim;
                    var args = string.Join(", ", call.Arguments.Select(EmitValue));
                    var fnName = call.IsForeignCall
                        ? call.FunctionName
                        : IrNameMangling.MangleFunctionName(call.FunctionName,
                            call.CalleeIrParamTypes
                            ?? (IReadOnlyList<IrType>)call.Arguments.Select(a => a.IrType ?? TypeLayoutService.IrI32).ToArray());

                    if (resultType == TypeLayoutService.IrVoidPrim)
                        sb.AppendLine($"    {fnName}({args});");
                    else
                        sb.AppendLine($"    {IrTypeToCType(resultType)} {resultName} = {fnName}({args});");
                    break;
                }

            case CastInstruction cast:
                {
                    var resultName = SanitizeName(cast.Result.Name);
                    var resultType = IrTypeToCType(cast.Result.IrType ?? TypeLayoutService.IrI32);
                    var src = EmitValue(cast.Source);
                    sb.AppendLine($"    {resultType} {resultName} = ({resultType}){src};");
                    break;
                }

            case GetElementPtrInstruction gep:
                {
                    var resultName = SanitizeName(gep.Result.Name);
                    var resultType = IrTypeToCType(gep.Result.IrType ?? TypeLayoutService.IrVoidPrim);
                    var basePtr = EmitValue(gep.BasePointer);
                    var offset = EmitValue(gep.ByteOffset);
                    sb.AppendLine($"    {resultType} {resultName} = ({resultType})((uint8_t*){basePtr} + {offset});");
                    break;
                }

            case BranchInstruction branch:
                {
                    var cond = EmitValue(branch.Condition);
                    sb.AppendLine($"    if ({cond}) goto {branch.TrueBlock.Label};");
                    sb.AppendLine($"    goto {branch.FalseBlock.Label};");
                    break;
                }

            case JumpInstruction jump:
                sb.AppendLine($"    goto {jump.TargetBlock.Label};");
                break;

            case AddressOfInstruction addrOf:
                {
                    var resultName = SanitizeName(addrOf.Result.Name);
                    var resultType = IrTypeToCType(addrOf.Result.IrType ?? TypeLayoutService.IrVoidPrim);
                    sb.AppendLine($"    {resultType} {resultName} = &{SanitizeName(addrOf.VariableName)};");
                    break;
                }

            default:
                sb.AppendLine($"    /* TODO: {inst.GetType().Name} */");
                break;
        }
    }

    // =========================================================================
    // Value emission
    // =========================================================================

    private static string EmitValue(Value value)
    {
        return value switch
        {
            ConstantValue cv => cv.IntValue.ToString(),
            LocalValue lv => SanitizeName(lv.Name),
            StringTableValue stv => $"__flang__string_table[{stv.Index}]",
            FunctionReferenceValue fv => SanitizeName(fv.Name),
            _ => $"/* unknown value: {value.GetType().Name} */"
        };
    }

    // =========================================================================
    // Type mapping
    // =========================================================================

    private static string IrTypeToCType(IrType? type)
    {
        return type switch
        {
            null => "void",
            IrPrimitive p => p.Name switch
            {
                "void" => "void",
                "never" => "void",
                "bool" => "bool",
                "i8" => "int8_t",
                "i16" => "int16_t",
                "i32" => "int32_t",
                "i64" => "int64_t",
                "u8" => "uint8_t",
                "u16" => "uint16_t",
                "u32" => "uint32_t",
                "u64" => "uint64_t",
                "isize" => "int64_t",
                "usize" => "uint64_t",
                "char" => "uint32_t",
                _ => "int32_t"
            },
            IrPointer ptr => $"{IrTypeToCType(ptr.Pointee)}*",
            IrArray arr => $"{IrTypeToCType(arr.Element)}*",
            IrStruct s => s.CName,
            IrEnum e => e.CName,
            IrFunctionPtr fp =>
                $"{IrTypeToCType(fp.Return)}(*)({string.Join(", ", fp.Params.Select(IrTypeToCType))})",
            _ => "void"
        };
    }

    private static string BinaryOpToC(BinaryOp op)
    {
        return op switch
        {
            BinaryOp.Add => "+",
            BinaryOp.Subtract => "-",
            BinaryOp.Multiply => "*",
            BinaryOp.Divide => "/",
            BinaryOp.Modulo => "%",
            BinaryOp.Equal => "==",
            BinaryOp.NotEqual => "!=",
            BinaryOp.LessThan => "<",
            BinaryOp.GreaterThan => ">",
            BinaryOp.LessThanOrEqual => "<=",
            BinaryOp.GreaterThanOrEqual => ">=",
            BinaryOp.BitwiseAnd => "&",
            BinaryOp.BitwiseOr => "|",
            BinaryOp.BitwiseXor => "^",
            BinaryOp.ShiftLeft => "<<",
            BinaryOp.ShiftRight => ">>",
            _ => "/* unknown op */"
        };
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    private static string MangleFunctionName(IrFunction fn)
    {
        return IrNameMangling.MangleFunctionName(fn.Name, fn.Params.Select(p => p.Type).ToArray());
    }

    private static string SanitizeName(string name)
    {
        // Replace characters that are invalid in C identifiers
        return name.Replace('.', '_').Replace('[', '_').Replace(']', '_')
            .Replace(',', '_').Replace(' ', '_').Replace('-', '_');
    }

    private static string EscapeString(string s)
    {
        return s.Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t")
            .Replace("\0", "\\0");
    }
}
